/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteerRouteImport } from './routes/volunteer'
import { Route as NgoRouteImport } from './routes/ngo'
import { Route as CitizenRouteImport } from './routes/citizen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolunteerIndexRouteImport } from './routes/volunteer.index'
import { Route as NgoIndexRouteImport } from './routes/ngo.index'
import { Route as VolunteerProfileRouteImport } from './routes/volunteer.profile'
import { Route as VolunteerOpportunitiesRouteImport } from './routes/volunteer.opportunities'
import { Route as VolunteerActivityRouteImport } from './routes/volunteer.activity'
import { Route as NgoPostRouteImport } from './routes/ngo.post'

const VolunteerRoute = VolunteerRouteImport.update({
  id: '/volunteer',
  path: '/volunteer',
  getParentRoute: () => rootRouteImport,
} as any)
const NgoRoute = NgoRouteImport.update({
  id: '/ngo',
  path: '/ngo',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenRoute = CitizenRouteImport.update({
  id: '/citizen',
  path: '/citizen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolunteerIndexRoute = VolunteerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VolunteerRoute,
} as any)
const NgoIndexRoute = NgoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NgoRoute,
} as any)
const VolunteerProfileRoute = VolunteerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerOpportunitiesRoute = VolunteerOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => VolunteerRoute,
} as any)
const VolunteerActivityRoute = VolunteerActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => VolunteerRoute,
} as any)
const NgoPostRoute = NgoPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => NgoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/ngo': typeof NgoRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/ngo/post': typeof NgoPostRoute
  '/volunteer/activity': typeof VolunteerActivityRoute
  '/volunteer/opportunities': typeof VolunteerOpportunitiesRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ngo/': typeof NgoIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/ngo/post': typeof NgoPostRoute
  '/volunteer/activity': typeof VolunteerActivityRoute
  '/volunteer/opportunities': typeof VolunteerOpportunitiesRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ngo': typeof NgoIndexRoute
  '/volunteer': typeof VolunteerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/citizen': typeof CitizenRoute
  '/ngo': typeof NgoRouteWithChildren
  '/volunteer': typeof VolunteerRouteWithChildren
  '/ngo/post': typeof NgoPostRoute
  '/volunteer/activity': typeof VolunteerActivityRoute
  '/volunteer/opportunities': typeof VolunteerOpportunitiesRoute
  '/volunteer/profile': typeof VolunteerProfileRoute
  '/ngo/': typeof NgoIndexRoute
  '/volunteer/': typeof VolunteerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/citizen'
    | '/ngo'
    | '/volunteer'
    | '/ngo/post'
    | '/volunteer/activity'
    | '/volunteer/opportunities'
    | '/volunteer/profile'
    | '/ngo/'
    | '/volunteer/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/citizen'
    | '/ngo/post'
    | '/volunteer/activity'
    | '/volunteer/opportunities'
    | '/volunteer/profile'
    | '/ngo'
    | '/volunteer'
  id:
    | '__root__'
    | '/'
    | '/citizen'
    | '/ngo'
    | '/volunteer'
    | '/ngo/post'
    | '/volunteer/activity'
    | '/volunteer/opportunities'
    | '/volunteer/profile'
    | '/ngo/'
    | '/volunteer/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CitizenRoute: typeof CitizenRoute
  NgoRoute: typeof NgoRouteWithChildren
  VolunteerRoute: typeof VolunteerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteer': {
      id: '/volunteer'
      path: '/volunteer'
      fullPath: '/volunteer'
      preLoaderRoute: typeof VolunteerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ngo': {
      id: '/ngo'
      path: '/ngo'
      fullPath: '/ngo'
      preLoaderRoute: typeof NgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen': {
      id: '/citizen'
      path: '/citizen'
      fullPath: '/citizen'
      preLoaderRoute: typeof CitizenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/volunteer/': {
      id: '/volunteer/'
      path: '/'
      fullPath: '/volunteer/'
      preLoaderRoute: typeof VolunteerIndexRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/ngo/': {
      id: '/ngo/'
      path: '/'
      fullPath: '/ngo/'
      preLoaderRoute: typeof NgoIndexRouteImport
      parentRoute: typeof NgoRoute
    }
    '/volunteer/profile': {
      id: '/volunteer/profile'
      path: '/profile'
      fullPath: '/volunteer/profile'
      preLoaderRoute: typeof VolunteerProfileRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/opportunities': {
      id: '/volunteer/opportunities'
      path: '/opportunities'
      fullPath: '/volunteer/opportunities'
      preLoaderRoute: typeof VolunteerOpportunitiesRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/volunteer/activity': {
      id: '/volunteer/activity'
      path: '/activity'
      fullPath: '/volunteer/activity'
      preLoaderRoute: typeof VolunteerActivityRouteImport
      parentRoute: typeof VolunteerRoute
    }
    '/ngo/post': {
      id: '/ngo/post'
      path: '/post'
      fullPath: '/ngo/post'
      preLoaderRoute: typeof NgoPostRouteImport
      parentRoute: typeof NgoRoute
    }
  }
}

interface NgoRouteChildren {
  NgoPostRoute: typeof NgoPostRoute
  NgoIndexRoute: typeof NgoIndexRoute
}

const NgoRouteChildren: NgoRouteChildren = {
  NgoPostRoute: NgoPostRoute,
  NgoIndexRoute: NgoIndexRoute,
}

const NgoRouteWithChildren = NgoRoute._addFileChildren(NgoRouteChildren)

interface VolunteerRouteChildren {
  VolunteerActivityRoute: typeof VolunteerActivityRoute
  VolunteerOpportunitiesRoute: typeof VolunteerOpportunitiesRoute
  VolunteerProfileRoute: typeof VolunteerProfileRoute
  VolunteerIndexRoute: typeof VolunteerIndexRoute
}

const VolunteerRouteChildren: VolunteerRouteChildren = {
  VolunteerActivityRoute: VolunteerActivityRoute,
  VolunteerOpportunitiesRoute: VolunteerOpportunitiesRoute,
  VolunteerProfileRoute: VolunteerProfileRoute,
  VolunteerIndexRoute: VolunteerIndexRoute,
}

const VolunteerRouteWithChildren = VolunteerRoute._addFileChildren(
  VolunteerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CitizenRoute: CitizenRoute,
  NgoRoute: NgoRouteWithChildren,
  VolunteerRoute: VolunteerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

